# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class CommunicatorStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Poll = channel.unary_stream(
        '/communicaiton.Communicator/Poll',
        request_serializer=helloworld__pb2.EmptyMessage.SerializeToString,
        response_deserializer=helloworld__pb2.Musician.FromString,
        )
    self.Send = channel.unary_unary(
        '/communicaiton.Communicator/Send',
        request_serializer=helloworld__pb2.Musician.SerializeToString,
        response_deserializer=helloworld__pb2.EmptyMessage.FromString,
        )


class CommunicatorServicer(object):
  """The greeting service definition.
  """

  def Poll(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Poll': grpc.unary_stream_rpc_method_handler(
          servicer.Poll,
          request_deserializer=helloworld__pb2.EmptyMessage.FromString,
          response_serializer=helloworld__pb2.Musician.SerializeToString,
      ),
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=helloworld__pb2.Musician.FromString,
          response_serializer=helloworld__pb2.EmptyMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communicaiton.Communicator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
